name: CI
on:
  release:
    types: [published]

jobs:
  build:
    name: Run Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org/

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
      - name: Generate TypeScript
        uses: borales/actions-yarn@v4
        with:
          cmd: build # will run `yarn build` command
      - name: Publish to NPM
        uses: borales/actions-yarn@v4
        with:
          cmd: publish --non-interactive
        env:
          YARN_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
